import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../app/theme/app_colors.dart';

/// In-app privacy policy.
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  static const effectiveDate = 'September 19, 2026';

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle.dark.copyWith(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: AppColors.canvas,
      ),
      child: Scaffold(
        body: SafeArea(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
                child: Align(
                  alignment: Alignment.centerLeft,
                  child: IconButton(
                    icon: const Icon(Icons.arrow_back_ios_new, size: 20),
                    color: AppColors.ink,
                    tooltip: 'Back',
                    onPressed: () => Navigator.of(context).maybePop(),
                  ),
                ),
              ),
              Expanded(
                child: ListView(
                  padding: const EdgeInsets.fromLTRB(20, 12, 20, 40),
                  children: const [
                    Text(
                      'Privacy policy',
                      style: TextStyle(
                        color: AppColors.ink,
                        fontSize: 26,
                        fontWeight: FontWeight.w600,
                        height: 1.2,
                      ),
                    ),
                    SizedBox(height: 8),
                    Text(
                      'Effective $effectiveDate',
                      style: TextStyle(
                        color: AppColors.secondary,
                        fontSize: 13,
                        height: 1.4,
                      ),
                    ),
                    SizedBox(height: 18),
                    Text(
                      'This Privacy Policy explains how Cura accesses, uses, '
                      'stores, transmits, and deletes information. Cura is an '
                      'open-source medical document organizer. It does not '
                      'require an account and does not operate a '
                      'developer-controlled backend.',
                      style: _bodyStyle,
                    ),
                    SizedBox(height: 20),
                    _PolicySummary(),
                    SizedBox(height: 28),
                    _PolicySection(
                      number: '1',
                      title: 'Purpose and scope',
                      paragraphs: [
                        'Cura helps you scan, import, organize, search, export, '
                            'and ask questions about medical documents that you '
                            'choose to add. This policy applies to the Cura '
                            'Android app and its included features.',
                        'Cura organizes and explains your documents. It does '
                            'not diagnose conditions, recommend treatment, or '
                            'replace a qualified healthcare professional.',
                      ],
                    ),
                    _PolicySection(
                      number: '2',
                      title: 'Information Cura handles',
                      paragraphs: [
                        'The information Cura handles depends on the features '
                            'you use. Medical documents can contain highly '
                            'sensitive health and identity information.',
                      ],
                      bullets: [
                        'Document files and images that you scan or import, '
                            'including retained original PDFs.',
                        'Text recognized from documents, document titles, '
                            'types, dates, results, units, reference ranges, '
                            'notes, and tags.',
                        'Questions you ask, answers generated by an AI model, '
                            'saved Ask conversations, and the identifier of a '
                            'document cited in an answer.',
                        'Temporary microphone recordings and their '
                            'transcriptions when you choose voice input.',
                        'Medicine reminders you set: the medicine name as your '
                            'prescription printed it, the dose times, how long '
                            'the course runs, and the day you last ticked a '
                            'dose off as taken.',
                        'App preferences, model selections, cloud provider '
                            'settings, consent status, and downloaded model '
                            'files.',
                        'Device capability details such as RAM, processor, CPU '
                            'core count, GPU, and Vulkan support. Cura reads '
                            'these locally to recommend a suitable AI option.',
                      ],
                    ),
                    _PolicySection(
                      number: '3',
                      title: 'Scanning, PDF import, and OCR',
                      paragraphs: [
                        'Cura uses the ML Kit document scanner supplied through '
                            'Google Play services. Google Play services may '
                            'download the scanner models, scanning logic, and '
                            'scanner interface before first use. The scanner '
                            'returns cropped page images to Cura. Cura then '
                            'copies those pages into its private app storage.',
                        'Text recognition runs on the device. Cura reads the '
                            'page images, reconstructs reading order, and parses '
                            'tables and receipt rows from OCR geometry. In the '
                            'default on-device mode, Cura does not upload the '
                            'document image, PDF, or recognized text for '
                            'scanning.',
                        'When you import a PDF, Android\'s system picker gives '
                            'Cura access only to the file you select. Cura '
                            'copies the original PDF into private storage, '
                            'renders up to 20 pages locally, and sends the '
                            'rendered pages through the same local OCR process.',
                        'An AI model may refine a document title, type, date, or '
                            'summary, and on a lab report it may identify '
                            'result rows the table parser missed. Labels and '
                            'numeric values returned by a model are checked '
                            'against the full local OCR before they can be '
                            'stored, and a row already read from the page is '
                            'never replaced. You should still review every '
                            'extracted field before saving.',
                      ],
                    ),
                    _PolicySection(
                      number: '4',
                      title: 'On-device AI models',
                      paragraphs: [
                        'On-device AI is the default. The selected model runs '
                            'inside Cura on your phone. Inference does not '
                            'require sending your question or document content '
                            'to a remote AI provider.',
                        'For Ask, the local model can receive your current '
                            'question, a limited amount of recent conversation '
                            'history, and relevant content retrieved from your '
                            'saved Cura documents. For scan refinement, it can '
                            'receive a selected OCR excerpt. The model can '
                            'generate text but cannot independently open other '
                            'apps, browse your phone, use the microphone, or '
                            'read files you have not added to Cura.',
                        'AI and voice model files are downloaded only when you '
                            'choose to download them. The model host or its '
                            'content delivery network receives a normal download '
                            'request, which can include your IP address and '
                            'standard network metadata. Cura does not attach '
                            'your medical documents or questions to a model '
                            'download request.',
                      ],
                    ),
                    _PolicySection(
                      number: '5',
                      title: 'Optional cloud models',
                      paragraphs: [
                        'Cloud models are off by default. You must provide your '
                            'own API key, choose a provider and model, enable the '
                            'cloud option, and accept a disclosure before Cura '
                            'sends a cloud request. You can switch back to an '
                            'on-device model at any time.',
                        'Cura supports OpenRouter, OpenAI, Groq, NVIDIA NIM, and '
                            'custom OpenAI-compatible endpoints. The provider '
                            'you select is a separate third party. Its terms, '
                            'privacy policy, security practices, retention, '
                            'training rules, and processing locations apply to '
                            'the request it receives.',
                      ],
                      bullets: [
                        'For Ask, Cura can send a minimized version of your '
                            'question, limited recent conversation history, '
                            'safe document titles or replacement titles, '
                            'document types and dates, relevant structured '
                            'results, and selected medical notes or excerpts.',
                        'For cloud scan refinement, Cura sends minimized OCR '
                            'text or sanitized table-cell evidence. Receipts use '
                            'a bill-specific allowlist. Cura does not '
                            'intentionally send page images, original PDFs, '
                            'local file paths, or unrestricted raw OCR.',
                        'The request includes model instructions and the model '
                            'identifier. Your API key is sent to the configured '
                            'provider in the authorization header so the '
                            'provider can authenticate the request.',
                        'The provider can receive your IP address, request '
                            'timing, and other standard connection metadata.',
                      ],
                      closing:
                          'Do not enable a cloud model unless you have reviewed '
                          'and accept the selected provider\'s data practices.',
                    ),
                    _PolicySection(
                      number: '6',
                      title: 'PII minimization for cloud requests',
                      paragraphs: [
                        'Before document-derived text reaches the cloud '
                            'boundary, Cura applies deterministic minimization '
                            'and redaction on the phone. This process is '
                            'designed to reduce unnecessary personally '
                            'identifiable information, often called PII.',
                      ],
                      bullets: [
                        'An allowlist keeps medical results, ranges, verdicts, '
                            'procedure names, report dates, and relevant '
                            'clinical sections while dropping letterheads, '
                            'patient blocks, signatures, and administrative '
                            'footers.',
                        'Unsafe document titles are replaced with a generic '
                            'document type before transmission.',
                        'Additional rules remove or drop detected names, '
                            'addresses, locations, organizations, email '
                            'addresses, phone numbers, URLs, patient labels, '
                            'and long identifiers.',
                        'Name-shaped text is removed from surviving clinical '
                            'lines. Narrative text can fall back to structured '
                            'facts when too much unknown text remains.',
                        'User questions and prior messages receive separate '
                            'identity and identifier scrubbing. A final gate '
                            'blocks a request when known high-risk patterns '
                            'remain.',
                      ],
                      closing:
                          'No automated redactor is perfect. Cura does not '
                          'guarantee that cloud-bound text is anonymous or '
                          'free of every identifier. Medical details can also '
                          'identify a person when combined with outside '
                          'information. If that risk is unacceptable, keep the '
                          'on-device model selected.',
                    ),
                    _PolicySection(
                      number: '7',
                      title: 'Voice input',
                      paragraphs: [
                        'Voice input is optional. Cura requests microphone '
                            'access only when you start dictation. It records a '
                            'temporary audio file, transcribes that file on the '
                            'device with a downloaded Whisper model, places the '
                            'text in the Ask composer for your review, and '
                            'deletes the temporary recording after '
                            'transcription or cancellation.',
                        'Voice audio is not sent to Cura\'s developer or to an '
                            'AI provider. If a cloud model is active and you '
                            'submit the transcribed question, the resulting '
                            'text is minimized and sent as described in '
                            'Sections 5 and 6.',
                      ],
                    ),
                    _PolicySection(
                      number: '8',
                      title: 'Storage and security',
                      paragraphs: [
                        'Cura stores documents, recognized text, structured '
                            'fields, and Ask conversations in its Android app '
                            'sandbox. Scanned pages, imported PDFs, and model '
                            'files are also stored in app-private directories. '
                            'Other ordinary apps cannot directly read this '
                            'private storage unless the device security model '
                            'has been compromised.',
                        'Cura stores a cloud API key with Android-backed secure '
                            'storage. Non-secret cloud settings and app '
                            'preferences are stored in Android preferences. '
                            'The document database and media files are not '
                            'separately encrypted by Cura, so device encryption, '
                            'screen lock protection, operating-system security, '
                            'and physical control of the phone remain '
                            'important.',
                        'Depending on your Android version, device maker, '
                            'Google account, and backup settings, Android may '
                            'include some Cura private files, preferences, and '
                            'database data in an encrypted system backup or '
                            'device-to-device transfer. This is controlled by '
                            'Android rather than a Cura-operated service. Review '
                            'your device backup settings if you do not want '
                            'system backup or transfer.',
                        'PDFs you export are saved outside Cura\'s private '
                            'sandbox in a destination you choose or in the Cura '
                            'folder under Downloads. Those exported files are '
                            'subject to the access, sharing, sync, and backup '
                            'rules of that destination.',
                      ],
                    ),
                    _PolicySection(
                      number: '9',
                      title: 'Network access and third parties',
                      paragraphs: [
                        'Cura does not operate an analytics service, advertising '
                            'service, account service, or developer-controlled '
                            'cloud database. Cura does not sell personal data.',
                      ],
                      bullets: [
                        'Google Play services supplies the ML Kit document '
                            'scanner. Google states that ML Kit Android SDKs may '
                            'collect device and app information, per-installation '
                            'identifiers, performance metrics, API '
                            'configuration, input and output sizes, feature '
                            'events, and error codes for diagnostics and usage '
                            'analytics. Google states that this technical data '
                            'is encrypted in transit and is not transferred to '
                            'third parties. Google\'s own privacy terms apply.',
                        'Hugging Face and related content delivery networks can '
                            'be contacted when you request an AI or voice model '
                            'download.',
                        'GitHub is contacted to check for a newer version of '
                            'Cura only when you tap Check for updates in '
                            'Settings, Updates, or, if you turn on Check for '
                            'updates automatically there, at most once a day. '
                            'Automatic checking is off by default. The check '
                            'asks which version is latest and sends none of your '
                            'records. When you tap Update, the new app file is '
                            'downloaded from GitHub. Like any web request, both '
                            'show GitHub your IP address and standard network '
                            'metadata.',
                        'Your selected cloud AI provider is contacted only when '
                            'you configure and enable cloud processing or test '
                            'that cloud connection.',
                        'Android system services handle file picking, saving, '
                            'permissions, backups, and device transfers under '
                            'your Android and Google account settings.',
                      ],
                    ),
                    _PolicySection(
                      number: '10',
                      title: 'Permissions',
                      bullets: [
                        'Internet access is used for requested model downloads, '
                            'for optional cloud AI requests, and for the update '
                            'check and download when you allow them. Local '
                            'processing does not require a network request after '
                            'required models are available.',
                        'Permission to install apps is used only to install a '
                            'Cura update you chose to download. Android asks you '
                            'to allow it the first time, and will only install '
                            'an update signed by the same developer key as the '
                            'Cura you already have.',
                        'Microphone access is used only while you actively '
                            'record a voice question.',
                        'Cura does not request broad storage access. Android '
                            'system pickers provide access to files you choose '
                            'to import or destinations you choose for export.',
                        'Cura does not request location, contacts, SMS, '
                            'calendar, body sensor, or Health Connect access.',
                        'The scanning camera and gallery interface are provided '
                            'through the Google Play services document scanner. '
                            'Cura does not declare a separate Android camera '
                            'permission.',
                        'Medicine reminders use notification and alarm '
                            'permissions. Reminders are scheduled by your phone '
                            'and delivered by your phone. Medicine names and dose '
                            'times are never sent anywhere, and setting a '
                            'reminder makes no network request.',
                        'The restart permission lets Cura put your existing '
                            'reminders back after the phone reboots. It reads '
                            'nothing and sends nothing.',
                      ],
                    ),
                    _PolicySection(
                      number: '11',
                      title: 'Retention, deletion, and export',
                      paragraphs: [
                        'Cura keeps local data until you delete it, clear the '
                            'app\'s storage, or uninstall the app. Cura\'s '
                            'developer cannot view or remotely delete data that '
                            'exists only on your phone.',
                      ],
                      bullets: [
                        'Deleting an individual document removes its database '
                            'record, associated private scan or import files, '
                            'and any medicine reminders set from it.',
                        'Delete all data removes saved documents, private scan '
                            'images, retained imported PDFs, medicine reminders, '
                            'the cloud API key, and cloud configuration. It '
                            'switches Cura back to the on-device engine.',
                        'Ask conversations can be deleted individually from '
                            'Ask. Downloaded AI and voice model files can be '
                            'deleted from their Settings sections.',
                        'Exported PDFs are outside Cura\'s private storage and '
                            'must be deleted with the Files app or the service '
                            'where you chose to save them.',
                        'A cloud provider may retain request data under its own '
                            'terms. Deleting local Cura data does not delete '
                            'copies already received by that provider. Contact '
                            'the provider for its retention and deletion '
                            'options.',
                        'Android backups or device transfers may restore some '
                            'app data after reinstalling Cura. Backup deletion '
                            'is controlled through your Android or Google '
                            'account settings.',
                      ],
                    ),
                    _PolicySection(
                      number: '12',
                      title: 'Your choices and control',
                      bullets: [
                        'Choose which documents to add and review extracted '
                            'fields before saving.',
                        'Use only on-device models, or explicitly enable and '
                            'later disable a cloud provider.',
                        'Decline microphone access and type questions instead.',
                        'Edit or delete saved documents and Ask conversations.',
                        'Export selected documents and control the destination.',
                        'Delete cloud settings, downloaded models, local data, '
                            'or the Cura app.',
                      ],
                    ),
                    _PolicySection(
                      number: '13',
                      title: 'Children',
                      paragraphs: [
                        'Cura is not designed for children to use without the '
                            'involvement of a parent or legal guardian. Cura '
                            'does not create child accounts or knowingly '
                            'collect a child\'s information on a '
                            'developer-operated server. A guardian who allows a '
                            'child to use Cura should control the device, the '
                            'documents added, and whether a third-party cloud '
                            'provider is enabled.',
                      ],
                    ),
                    _PolicySection(
                      number: '14',
                      title: 'Changes to this policy',
                      paragraphs: [
                        'This policy may change when Cura\'s features or data '
                            'practices change. The effective date at the top '
                            'will be updated. Material changes should be '
                            'presented with an app update or another clear '
                            'notice before the changed practice takes effect.',
                      ],
                    ),
                    _PolicySection(
                      number: '15',
                      title: 'Developer and privacy contact',
                      paragraphs: [
                        'Cura is developed and maintained through the Cura '
                            'open-source project. Privacy questions and requests '
                            'can be submitted through the public issue tracker '
                            'at github.com/Tarun-032/cura/issues.',
                        'Do not include medical documents, API keys, names, '
                            'contact details, identifiers, or other sensitive '
                            'information in a public GitHub issue.',
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

const _bodyStyle = TextStyle(color: AppColors.ink, fontSize: 14, height: 1.65);

class _PolicySummary extends StatelessWidget {
  const _PolicySummary();

  @override
  Widget build(BuildContext context) {
    return const Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Summary',
          style: TextStyle(
            color: AppColors.ink,
            fontSize: 18,
            fontWeight: FontWeight.w600,
            height: 1.35,
          ),
        ),
        SizedBox(height: 10),
        _PolicyBullet(
          'Cura stores and processes your medical documents on your phone by '
          'default.',
        ),
        _PolicyBullet(
          'Cura has no accounts, ads, developer analytics, or '
          'developer-operated record server.',
        ),
        _PolicyBullet(
          'Cloud AI is optional. When enabled, minimized and redacted text is '
          'sent to the provider you choose.',
        ),
        _PolicyBullet(
          'Redaction lowers risk but cannot guarantee that medical text is '
          'anonymous.',
          bottomPadding: 0,
        ),
      ],
    );
  }
}

class _PolicySection extends StatelessWidget {
  const _PolicySection({
    required this.number,
    required this.title,
    this.paragraphs = const [],
    this.bullets = const [],
    this.closing,
  });

  final String number;
  final String title;
  final List<String> paragraphs;
  final List<String> bullets;
  final String? closing;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 26),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$number. $title',
            style: const TextStyle(
              color: AppColors.ink,
              fontSize: 18,
              fontWeight: FontWeight.w600,
              height: 1.35,
            ),
          ),
          const SizedBox(height: 10),
          for (var i = 0; i < paragraphs.length; i++) ...[
            Text(paragraphs[i], style: _bodyStyle),
            if (i < paragraphs.length - 1) const SizedBox(height: 10),
          ],
          if (paragraphs.isNotEmpty && bullets.isNotEmpty)
            const SizedBox(height: 10),
          for (var i = 0; i < bullets.length; i++)
            _PolicyBullet(
              bullets[i],
              bottomPadding: i == bullets.length - 1 ? 0 : 8,
            ),
          if (closing != null) ...[
            const SizedBox(height: 10),
            Text(closing!, style: _bodyStyle),
          ],
        ],
      ),
    );
  }
}

class _PolicyBullet extends StatelessWidget {
  const _PolicyBullet(this.text, {this.bottomPadding = 8});

  final String text;
  final double bottomPadding;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(bottom: bottomPadding),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Padding(
            padding: EdgeInsets.only(top: 8),
            child: SizedBox(
              width: 5,
              height: 5,
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: AppColors.accent,
                  shape: BoxShape.circle,
                ),
              ),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(child: Text(text, style: _bodyStyle)),
        ],
      ),
    );
  }
}
